name: Create OSX universal binary
description: Creates a MacOs universal binary
inputs:
  amd-64-binary-artifact:
    description: Artifact containing AMD64 arch binary to download
  amd-64-binary-name:
    description: AMD64 arch binary name
  arm-64-binary-artifact:
    description: Artifact containing ARM64 arch binary to download
  arm-64-binary-name:
    description: ARM64 arch binary name
  universal-output-binary-name:
    description: Name for the output universal binary
runs:
  using: composite
  steps:
    - name: Download OSX Editor Debug App x64
      uses: actions/download-artifact@v1
      with:
        name: ${{ inputs.amd-64-binary-artifact }}
    - name: Download OSX Editor Debug App arm64
      uses: actions/download-artifact@v1
      with:
        name: ${{ inputs.arm-64-binary-artifact }}
    - name: Create OSX universal binary
      shell: sh
      run: |
        lipo -create ${{ inputs.amd-64-binary-artifact }}/${{ inputs.amd-64-binary-name }} ${{ inputs.arm-64-binary-artifact }}/${{ inputs.arm-64-binary-name }} -output ${{ inputs.universal-output-binary-name }}
